language: python

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

script:
  - source .github/check_license.sh
  - source .github/check_python_scripts.sh

notifications:
  email: false
